name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: ${{ secrets.BACKEND_URL }}
      CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: rm frontend/.env && echo BACKEND_URL=$BACKEND_URL > frontend/.env
      - run: npm install --prefix frontend
      - run: npm run build --prefix frontend
      - run: rm backend/.env && echo CERTIFICATE_ARN=$CERTIFICATE_ARN > backend/.env
      - run: npm run cdk synth

#      - name: cdk deploy
#        uses: youyo/aws-cdk-github-actions@v2
#        with:
#          cdk_subcommand: 'deploy'
#          cdk_stack: '*'
#          cdk_args: ${{ format('--require-approval never') }}
#          working_dir: 'backend'
#          debug_log: true
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: 'us-east-1'
#          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
#          CDK_DEFAULT_REGION: 'us-east-1'