name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: ${{ secrets.BACKEND_URL }}
      CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - run: rm frontend/.env && echo BACKEND_URL=$BACKEND_URL > frontend/.env
      - run: npm install --prefix frontend
      - run: npm run build --prefix frontend

      - run: rm backend/.env && echo CERTIFICATE_ARN=$CERTIFICATE_ARN > backend/.env
      - run: npm install --prefix backend
      - run: npm run --prefix backend cdk deploy "*" -- --require-approval never